server:
  port: 8080

## data source
spring:
  datasource:
    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql



mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.anan.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug